### PR TITLE
Using Bootstrap

### PR DESCRIPTION
**Pull request by TSHEPO-CLOUD**
- In this milestone 7:
    Using Bootstrap
    Added bootstrap classes 
    Added markup for the clone page
    Added the linters (HTML & CSS) config
    Added clone stylesheet
    Added Media Query for responsiveness
    Add Clone screenshot to README
    Update README message

### CODE REVIEW

**Review by kevcap — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUIRED♻️

#### Hey @TSHEPO-CLOUD  and @CornerstoneII,  your project is looking really good, and we're almost there, to accomplish as the actual page, you required to do these minor changes, listed below:
 
_Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, to get more knowledge and have a better project to add at your portfolio.
 
 
## [REQUIRED CHANGES]
#### Good practices REQUIREMENTS (Those changes to make you code like a pro 👽)⤵
- [x] Your code is throwing some linter errors, please fix them! 💪
image
- [x] Your code is throwing some errors and warnings at the [HTML5 Validator](https://validator.w3.org/nu/#textarear), please fix them.
image

#### Clone REQUIREMENTS 👥 (Those adjusts to make your page really look like the real one)⤵
#### Medium screens issues:
- [x] In medium screens, newsletter section should be below the subscribe section, please fix that: 🤓
##### Yours:
image
##### Original:
image

#### Medium & Small screens issues:
- [x] Your navbar is too shrinked, make it more similar to the original one
##### Yours:
image
##### Original:
image

## [OPTIONAL CHANGES]
You guys did an amazing job, and your page meets most of the requirements. But I think you guys can go for that extra mile and work at the design to make the page a real clone. (Images, Headings, text, favicon, etc...)
- [x] Put your `css` files in a css folder. (To make your repo more professional)
- [x] Use `<main>` tag for the dominant content inside the `<body>` tag.

## Summary

✨ Your CSS looks really organized and professional! 👨‍💻
✨ The project looks really nice 💯
✨ Nice usage of the bootstrap!
✨ Good job with that project, it looks really good for a first review 💥
🔧 Please make the required changes and keep up the good work! 👨‍💻

68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f535873315842624179396169486542354c532f67697068792e676966
Gif credit: Our great TSE @lmaldonadoch 👷‍♂️
## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes :recycle: 
## Hi, you started well with the header it looks like the original :clap: :+1: :100:, but the whole page is not, you need to work more on your project :hammer: :wrench: :toolbox: otherwise it will not be approved :checkered_flag: please follow the design of the original page with the colors and everything until you feel like that you can't differentiate between your clone and the original website then request for a code review.

## Happy Coding :tophat:

**Review by MuriloRoque — CHANGES_REQUESTED** [review]
# Status: Changes requested :red_circle: 

### Hello @TSHEPO-CLOUD and @CornerstoneII :wave: 

### I see you have done some changes to your design after the last TSE review, but we still need to work on some issues, your whole page needs adjustments, you should follow the original design. I'm gonna give you some examples, but please try working on the whole page :pray: 

- [x] Your logo needs to be centered on the desktop view. Also, your 'Subscribe' button should be bigger, check my screenshots below:

***YOURS***

Screenshot from 2020-09-07 14-45-07
<br>

***ORIGINAL***

Screenshot from 2020-09-07 14-45-09
<br>

- [x] On tablet and mobile view, your 'Subscribe' button and icons need to change color and size, try matching the original:

***YOURS***
Screenshot from 2020-09-07 14-49-35
<br>

***ORIGINAL***

Screenshot from 2020-09-07 14-49-37
<br>

- [x] Your fonts and styling need to change a lot, I will show you only one screenshot below, but work with the entire page's fonts sizes, family, and colors:

***YOURS***
Screenshot from 2020-09-07 14-51-35
<br>

***ORIGINAL***

Screenshot from 2020-09-07 14-51-48
<br>

- [x] You need to work more in the 'The Debate' section, as it's not aligned correctly and your images are too big, check below:

***YOURS***
Screenshot from 2020-09-07 14-55-18
<br>

***ORIGINAL***

Screenshot from 2020-09-07 14-55-58
<br>

- [x] Please, work on the headings of each section, I'm going to show you one screenshot of the 'In the magazine' section, but you need to change all of them. They need to be centered, and with the Newsweek symbol by their side. Check below:

***YOURS***
Screenshot from 2020-09-07 14-55-23
<br>

***ORIGINAL***

Screenshot from 2020-09-07 14-56-18
<br>

### Kindly make the requested changes and submit for another review, please :pray: 

### I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Review by MuriloRoque — CHANGES_REQUESTED** [review]
## Status: Changes requested :red_circle: 

### Hello again @TSHEPO-CLOUD and @CornerstoneII :wave: 

### I can see that you have done some big changes since the last review, your page is a lot better :clap: 

### We only have one issue remaining, and it's because of one of the changes I requested:

- [x] On all screen sizes, there's an issue with the position of the labels in these images below. Remember that they should stay in the same position inside the images in ALL sizes:

Screenshot from 2020-09-10 13-35-42
<br>

Screenshot from 2020-09-10 13-35-55
<br>

Screenshot from 2020-09-10 13-36-01
<br>

### Kindly make the requested changes and submit for another review, please :pray: 

### I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Review by elmejdki — APPROVED** [review]
# status: approved :heavy_check_mark: 
## Great job guys :+1: :100: :clap:  

now you can merge to master your project is approved

## Happy Coding :tophat:

**Pull request merged**
